Lesson 202 - Deploy to Heroku - Part 3
2021-12-09T06:34:27.404929+00:00 app[web.1]: Error: Cannot find module '../models/user'
2021-12-09T06:34:27.404929+00:00 app[web.1]: Require stack:
2021-12-09T06:34:27.404930+00:00 app[web.1]: - /app/middleware/authentication.js
2021-12-09T06:34:27.404930+00:00 app[web.1]: - /app/app.js

https://www.udemy.com/course/nodejs-tutorial-and-projects-course/learn/lecture/27505720#overview